lib/talk_web/router.ex
defmodule TalkWeb.Router do
  use TalkWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TalkWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TalkWeb.Plugs.SetUser
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TalkWeb do
    pipe_through :browser

    get "/", TopicController, :index
    get "/new", TopicController, :new
    post "/create", TopicController, :create
    delete ":id/delete", TopicController, :delete
    put "update/:id", TopicController, :update
    get "edit/:id", TopicController, :edit
    get "/:id", TopicController, :show
  end

  scope "/auth", TalkWeb do
    pipe_through :browser

    get "/:provider",AuthController, :request
    get "/:provider/callback", AuthController, :callback
    put "/signout", AuthController, :signout

  end

  # Other scopes may use custom stacks.
  # scope "/api", TalkWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TalkWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

       defp put_user_token(conn, _) do
         if current_user = conn.assigns[:user] do
           token = Phoenix.Token.sign(conn, "user socket", current_user.id)
           assign(conn, :user_token, token)
         else
           conn
         end
       end
end

lib/talk_web/views/layout_view.ex
defmodule TalkWeb.LayoutView do
  use TalkWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/talk_web/templates/layout/app.html.heex
<script>window.userToken = "<%= assigns[:user_token] %>";</script>
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/talk_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/talk_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="csrf-token" content={csrf_token_value()}>
  <%= live_title_tag assigns[:page_title] || "Talk" , suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css" )} />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js" )}></script>
</head>

<body>
  <header>
    <section class="container">
      <nav>
        <ul>
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out" , to: Routes.auth_path(@conn, :signout), method: :put %>
            </li>
            <% else %>
              <li>
                <%= link "Sign with Github" , to: Routes.auth_path(@conn, :request, "github" ) %>
              </li>
              <% end %>
        </ul>
      </nav>

    </section>
  </header>
  <%= @inner_content %>
</body>

</html>